import * as THREE from 'https://esm.sh/three@0.179.1';
import { EffectComposer } from 'https://esm.sh/three@0.179.1/examples/jsm/postprocessing/EffectComposer.js';
import { RenderPass } from 'https://esm.sh/three@0.179.1/examples/jsm/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'https://esm.sh/three@0.179.1/examples/jsm/postprocessing/UnrealBloomPass.js';
import { SSAOPass } from 'https://esm.sh/three@0.179.1/examples/jsm/postprocessing/SSAOPass.js';
import { GLTFLoader } from 'https://esm.sh/three@0.179.1/examples/jsm/loaders/GLTFLoader.js';
import { RGBELoader } from 'https://esm.sh/three@0.179.1/examples/jsm/loaders/RGBELoader.js';

const viewport=document.querySelector('#viewport'), ui=document.querySelector('#ui'), garage=document.querySelector('#garage'), hud=document.querySelector('#hud'), toast=document.querySelector('#toast');
const speedEl=document.querySelector('#speed'), nitroEl=document.querySelector('#nitro'), driveModeEl=document.querySelector('#driveMode'), cameraModeEl=document.querySelector('#cameraMode'), carList=document.querySelector('#carList');
const coinEls=document.querySelectorAll('[data-coins]'), carEls=document.querySelectorAll('[data-car]');
const VEHICLES=[
 {id:'toycar',name:'GLTF Sports Coupe',price:0,color:0xd8dde6,accent:0x0b1220,speed:42,grip:.9,source:'Khronos glTF Sample Models',license:'free sample asset',url:'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/ToyCar/glTF-Binary/ToyCar.glb'},
 {id:'truck',name:'GLTF Utility Truck',price:2000,color:0x2a7fff,accent:0x05070c,speed:35,grip:.82,source:'Khronos glTF Sample Models',license:'free sample asset',url:'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/CesiumMilkTruck/glTF/CesiumMilkTruck.gltf'}
];
const ASSETS={hdri:'https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/outdoor_workshop_1k.hdr'};
const state=JSON.parse(localStorage.getItem('sd-vehicle-save')||'null')||{coins:0,owned:['toycar'],selected:'toycar'};
const rig={root:new THREE.Group(),model:null,wheels:[],steering:[],brakes:[],body:null,spin:0,steer:0,suspension:0,camera:'orbit',turntable:0};
const scene=new THREE.Scene(); scene.fog=new THREE.FogExp2(0x080b14,.018);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.05,500); camera.position.set(5,2.4,7);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.08; renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; viewport.append(renderer.domElement);
const composer=new EffectComposer(renderer); composer.addPass(new RenderPass(scene,camera)); const ssao=new SSAOPass(scene,camera,innerWidth,innerHeight); ssao.kernelRadius=18; ssao.minDistance=.002; ssao.maxDistance=.16; composer.addPass(ssao); composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.3,.5,.86));
scene.add(rig.root); const hemi=new THREE.HemisphereLight(0xdcecff,0x111318,1.1), key=new THREE.DirectionalLight(0xffffff,5.2), rim=new THREE.DirectionalLight(0x7dc7ff,2.6); key.position.set(-6,8,5); key.castShadow=true; key.shadow.mapSize.set(2048,2048); key.shadow.camera.near=.2; key.shadow.camera.far=80; key.shadow.camera.left=-12; key.shadow.camera.right=12; key.shadow.camera.top=12; key.shadow.camera.bottom=-12; rim.position.set(7,4,-7); scene.add(hemi,key,rim);
new RGBELoader().load(ASSETS.hdri,h=>{h.mapping=THREE.EquirectangularReflectionMapping; scene.environment=h; scene.background=h;});
const floor=new THREE.Mesh(new THREE.CircleGeometry(7,96),new THREE.MeshStandardMaterial({color:0x11151c,metalness:.15,roughness:.22,envMapIntensity:1.25})); floor.rotation.x=-Math.PI/2; floor.receiveShadow=true; scene.add(floor);
const loader=new GLTFLoader();
function vehicle(){return VEHICLES.find(v=>v.id===state.selected)||VEHICLES[0];} function save(){localStorage.setItem('sd-vehicle-save',JSON.stringify(state));}
function sync(){coinEls.forEach(e=>e.textContent=Math.floor(state.coins)); carEls.forEach(e=>e.textContent=vehicle().name); renderGarage();}
function show(panel){[ui,garage,hud].forEach(e=>e.classList.add('hidden')); panel.classList.remove('hidden');}
function notify(text){toast.textContent=text;toast.classList.remove('hidden');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.add('hidden'),2200);} function reward(n){state.coins+=n;save();sync();notify(`+${n} монет`);}
function paintMaterial(v){return new THREE.MeshPhysicalMaterial({color:v.color,metalness:.86,roughness:.18,clearcoat:1,clearcoatRoughness:.08,reflectivity:1,envMapIntensity:1.8});}
function glassMaterial(){return new THREE.MeshPhysicalMaterial({color:0xbbe8ff,metalness:0,roughness:.02,transmission:.55,thickness:.16,transparent:true,opacity:.58,envMapIntensity:2});}
function tuneMaterials(root,v){root.traverse(o=>{if(!o.isMesh)return; o.castShadow=true; o.receiveShadow=true; const n=o.name.toLowerCase(); if(/glass|window|windshield/.test(n))o.material=glassMaterial(); else if(/tire|rubber/.test(n))o.material=new THREE.MeshStandardMaterial({color:0x050505,roughness:.52,metalness:.04}); else if(/brake|disc|rotor|rim|wheel/.test(n))o.material=new THREE.MeshStandardMaterial({color:0xbcc3cc,metalness:.9,roughness:.16,envMapIntensity:1.5}); else if(/light|lamp|head/.test(n))o.material=new THREE.MeshStandardMaterial({color:0xfff4d0,emissive:0xffe7aa,emissiveIntensity:1.7}); else if(/tail|brake/.test(n))o.material=new THREE.MeshStandardMaterial({color:0xff1835,emissive:0xff0014,emissiveIntensity:1.8}); else o.material=paintMaterial(v);});}
function bindRig(root){rig.wheels=[]; rig.steering=[]; rig.brakes=[]; rig.body=root; const box=new THREE.Box3().setFromObject(root), center=box.getCenter(new THREE.Vector3()), size=box.getSize(new THREE.Vector3()); root.position.sub(center); root.position.y+=size.y*.5; const scale=4.6/Math.max(size.x,size.y,size.z); root.scale.setScalar(scale); root.traverse(o=>{const n=o.name.toLowerCase(); if(/wheel|tire|rim/.test(n)){rig.wheels.push(o); if(o.getWorldPosition(new THREE.Vector3()).z<0)rig.steering.push(o);} if(/brake|disc|rotor/.test(n))rig.brakes.push(o);});}
async function loadSelectedVehicle(){const v=vehicle(); notify(`Загрузка ${v.name}`); const gltf=await loader.loadAsync(v.url); rig.root.clear(); rig.model=gltf.scene; tuneMaterials(rig.model,v); bindRig(rig.model); rig.root.add(rig.model); notify(`${v.name}: GLTF asset loaded`);}
function renderGarage(){carList.innerHTML=VEHICLES.map(v=>{const owned=state.owned.includes(v.id),active=state.selected===v.id;return `<article class="car-card"><h3>${v.name}</h3><p>${v.source} • ${v.license}</p>${bar('Скорость',v.speed/42)}${bar('Сцепление',v.grip)}<button data-buy="${v.id}" ${active?'disabled':''}>${owned?(active?'В студии':'Загрузить'):'Купить за '+v.price}</button></article>`}).join('');}
function bar(label,value){return `<small>${label}</small><div class="bar"><i style="width:${Math.round(value*100)}%"></i></div>`;}
function animateRig(dt){rig.turntable+=dt*.18; rig.spin+=dt*(speedEl.dataset.motion==='1'?12:2.6); rig.steer=THREE.MathUtils.lerp(rig.steer,(Math.sin(performance.now()*.0012))*0.42,dt*4); rig.suspension=Math.sin(performance.now()*.004)*.035; rig.root.rotation.y=rig.turntable; if(rig.model)rig.model.position.y=rig.suspension; rig.wheels.forEach(w=>{w.rotation.x-=dt*rig.spin;}); rig.steering.forEach(w=>{w.rotation.y=rig.steer;}); const orbit=rig.camera==='interior'?new THREE.Vector3(.15,1.2,.15):new THREE.Vector3(Math.sin(rig.turntable)*6,2.2,Math.cos(rig.turntable)*6); camera.position.lerp(orbit,dt*3); camera.lookAt(0,rig.camera==='interior'?1.05:.75,0); speedEl.textContent=speedEl.dataset.motion==='1'?'120':'0'; nitroEl.textContent='100'; driveModeEl.textContent='Vehicle Studio'; cameraModeEl.textContent=rig.camera==='interior'?'Interior':'Exterior';}
function loop(){const dt=Math.min(.033,clock.getDelta()); animateRig(dt); composer.render(); requestAnimationFrame(loop);} const clock=new THREE.Clock(); loop();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight; camera.updateProjectionMatrix(); renderer.setSize(innerWidth,innerHeight); composer.setSize(innerWidth,innerHeight);});
document.addEventListener('keydown',e=>{if(e.code==='KeyC')rig.camera=rig.camera==='interior'?'orbit':'interior'; if(e.code==='Space')speedEl.dataset.motion=speedEl.dataset.motion==='1'?'0':'1';});
document.addEventListener('click',async e=>{const a=e.target.closest('[data-action],[data-buy]'); if(!a)return; if(a.dataset.action==='play'){show(hud); await loadSelectedVehicle();} if(a.dataset.action==='garage')show(garage); if(a.dataset.action==='menu')show(ui); if(a.dataset.action==='camera')rig.camera=rig.camera==='interior'?'orbit':'interior'; if(a.dataset.action==='reward1000')reward(1000); if(a.dataset.action==='reward2000')reward(2000); if(a.dataset.buy){const v=VEHICLES.find(x=>x.id===a.dataset.buy); if(state.owned.includes(v.id)){state.selected=v.id; await loadSelectedVehicle();} else if(state.coins>=v.price){state.coins-=v.price; state.owned.push(v.id); state.selected=v.id; save(); sync(); await loadSelectedVehicle();} else notify('Недостаточно монет'); sync();}});
sync(); show(ui); loadSelectedVehicle();
