import * as THREE from 'https://esm.sh/three@0.179.1';
import { EffectComposer } from 'https://esm.sh/three@0.179.1/examples/jsm/postprocessing/EffectComposer.js';
import { RenderPass } from 'https://esm.sh/three@0.179.1/examples/jsm/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'https://esm.sh/three@0.179.1/examples/jsm/postprocessing/UnrealBloomPass.js';
import { SSAOPass } from 'https://esm.sh/three@0.179.1/examples/jsm/postprocessing/SSAOPass.js';
import { GLTFLoader } from 'https://esm.sh/three@0.179.1/examples/jsm/loaders/GLTFLoader.js';
import { RGBELoader } from 'https://esm.sh/three@0.179.1/examples/jsm/loaders/RGBELoader.js';

const viewport=document.querySelector('#viewport'), ui=document.querySelector('#ui'), modes=document.querySelector('#modes'), garage=document.querySelector('#garage'), hud=document.querySelector('#hud'), toast=document.querySelector('#toast');
const speedEl=document.querySelector('#speed'), nitroEl=document.querySelector('#nitro'), driveModeEl=document.querySelector('#driveMode'), cameraModeEl=document.querySelector('#cameraMode'), carList=document.querySelector('#carList');
const coinEls=document.querySelectorAll('[data-coins]'), carEls=document.querySelectorAll('[data-car]');
const cars=[
 {id:'zhiguli',name:'Жигуль',price:0,color:0xcfd8df,accent:0x8593a3,speed:42,accel:18,grip:.82,nitro:18,brake:24,mass:1250},
 {id:'bmw',name:'BMW M5 F90',price:2000,color:0x1b7fff,accent:0x050a14,speed:56,accel:25,grip:.94,nitro:27,brake:32,mass:1850},
 {id:'dodge',name:'Dodge Challenger',price:5000,color:0xff7a18,accent:0x15100a,speed:61,accel:27,grip:.9,nitro:31,brake:30,mass:1950},
 {id:'ferrari',name:'Ferrari',price:10000,color:0xe90024,accent:0x200006,speed:70,accel:35,grip:1.06,nitro:36,brake:42,mass:1450},
 {id:'bugatti',name:'Bugatti',price:20000,color:0x1b2cff,accent:0x02030a,speed:82,accel:39,grip:1.08,nitro:44,brake:44,mass:1650},
 {id:'formula',name:'Formula 1',price:50000,color:0xf5f7fb,accent:0xd71920,speed:92,accel:48,grip:1.34,nitro:50,brake:58,mass:820}
];
const state=JSON.parse(localStorage.getItem('sd3d-save')||'null')||{coins:0,owned:['zhiguli'],selected:'zhiguli'};
const game={running:false,mode:'day',camera:'third',drift:false,keys:{},speed:0,sideVel:0,nitro:100,coins:[],traffic:[],clock:new THREE.Clock(),distance:0};
const scene=new THREE.Scene(); scene.fog=new THREE.FogExp2(0x9ec9ff,.006);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,1800);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.8)); renderer.setSize(innerWidth,innerHeight); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.05; renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; viewport.append(renderer.domElement);
const composer=new EffectComposer(renderer); composer.addPass(new RenderPass(scene,camera)); const ssao=new SSAOPass(scene,camera,innerWidth,innerHeight); ssao.kernelRadius=14; ssao.minDistance=.003; ssao.maxDistance=.12; composer.addPass(ssao); composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.38,.55,.82));
const hemi=new THREE.HemisphereLight(0xbfdcff,0x243018,1.7); scene.add(hemi); const sun=new THREE.DirectionalLight(0xfff0c2,4.8); sun.position.set(-120,180,80); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); sun.shadow.camera.near=1; sun.shadow.camera.far=520; sun.shadow.camera.left=-180; sun.shadow.camera.right=180; sun.shadow.camera.top=180; sun.shadow.camera.bottom=-180; scene.add(sun);
const ASSETS={toyCar:'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/ToyCar/glTF-Binary/ToyCar.glb',truck:'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/CesiumMilkTruck/glTF/CesiumMilkTruck.gltf',hdri:'https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/outdoor_workshop_1k.hdr',asphalt:{map:'https://dl.polyhaven.org/file/ph-assets/Textures/jpg/1k/asphalt_02/asphalt_02_diff_1k.jpg',normal:'https://dl.polyhaven.org/file/ph-assets/Textures/jpg/1k/asphalt_02/asphalt_02_nor_gl_1k.jpg',rough:'https://dl.polyhaven.org/file/ph-assets/Textures/jpg/1k/asphalt_02/asphalt_02_rough_1k.jpg'}};
const textureLoader=new THREE.TextureLoader(), gltfLoader=new GLTFLoader();
const roadMat=new THREE.MeshStandardMaterial({color:0x20242b,roughness:.42,metalness:.08,envMapIntensity:.8}); const wetMat=new THREE.MeshStandardMaterial({color:0x161b22,roughness:.18,metalness:.22,envMapIntensity:1.4}); const grassMat=new THREE.MeshStandardMaterial({color:0x236b2d,roughness:.85});
function loadTexture(url, target, slot){textureLoader.load(url,t=>{t.wrapS=t.wrapT=THREE.RepeatWrapping; t.repeat.set(8,28); t.colorSpace=slot==='map'?THREE.SRGBColorSpace:THREE.NoColorSpace; target[slot]=t; target.needsUpdate=true;});}
loadTexture(ASSETS.asphalt.map,roadMat,'map'); loadTexture(ASSETS.asphalt.normal,roadMat,'normalMap'); loadTexture(ASSETS.asphalt.rough,roadMat,'roughnessMap'); loadTexture(ASSETS.asphalt.map,wetMat,'map'); loadTexture(ASSETS.asphalt.normal,wetMat,'normalMap');
new RGBELoader().load(ASSETS.hdri,h=>{h.mapping=THREE.EquirectangularReflectionMapping; scene.environment=h; scene.background=h;});
const world=new THREE.Group(), trafficGroup=new THREE.Group(), coinGroup=new THREE.Group(); scene.add(world,trafficGroup,coinGroup);
const player=new THREE.Group(); scene.add(player); let playerBody; const vehicleAssets={car:null,truck:null,ready:false};
function save(){localStorage.setItem('sd3d-save',JSON.stringify(state));} function car(){return cars.find(c=>c.id===state.selected)||cars[0];}
function sync(){coinEls.forEach(e=>e.textContent=Math.floor(state.coins)); carEls.forEach(e=>e.textContent=car().name); renderGarage();}
function show(x){[ui,modes,garage,hud].forEach(e=>e.classList.add('hidden')); x.classList.remove('hidden'); game.running=x===hud;}
function notify(t){toast.textContent=t;toast.classList.remove('hidden');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.add('hidden'),1800);} function reward(n){state.coins+=n;save();sync();notify(`+${n} монет за рекламу`);}
function mat(color,metal=.75,rough=.25){return new THREE.MeshPhysicalMaterial({color,metalness:metal,roughness:rough,clearcoat:1,clearcoatRoughness:.12,reflectivity:1});}
function mesh(g,m,pos,cast=true){const o=new THREE.Mesh(g,m); o.position.copy(pos||new THREE.Vector3()); o.castShadow=cast; o.receiveShadow=true; return o;}
function tuneVehicleModel(root,c){
 root.traverse(o=>{if(o.isMesh){o.castShadow=true; o.receiveShadow=true; const name=(o.name||'').toLowerCase(); if(name.includes('glass')||name.includes('window')){o.material=new THREE.MeshPhysicalMaterial({color:0x9edcff,metalness:0,roughness:.03,transmission:.45,transparent:true,opacity:.52,envMapIntensity:1.8});} else if(name.includes('wheel')||name.includes('tire')){o.material=new THREE.MeshStandardMaterial({color:0x050505,roughness:.48,metalness:.05});} else {o.material=mat(c.color,.82,.2);}}});
 return root;
}
async function loadVehicleAssets(){
 const [toy,truck]=await Promise.all([gltfLoader.loadAsync(ASSETS.toyCar),gltfLoader.loadAsync(ASSETS.truck)]);
 vehicleAssets.car=toy.scene; vehicleAssets.truck=truck.scene; vehicleAssets.ready=true; rebuildPlayer();
}
loadVehicleAssets().catch(e=>notify(`Не удалось загрузить GLTF модели: ${e.message}`));
function createCar(c,traffic=false){
 const source=(traffic&&vehicleAssets.truck?vehicleAssets.truck:vehicleAssets.car);
 if(!source) return new THREE.Group();
 const g=tuneVehicleModel(source.clone(true),c);
 const box=new THREE.Box3().setFromObject(g), size=box.getSize(new THREE.Vector3());
 const scale=(traffic?4.6:4.35)/Math.max(size.x,size.y,size.z);
 g.scale.setScalar(scale); g.rotation.y=Math.PI; g.position.y=.08;
 return g;
}
function rebuildPlayer(){player.clear(); playerBody=createCar(car()); player.add(playerBody);} rebuildPlayer();
function createWorld(mode='day'){world.clear(); trafficGroup.clear(); coinGroup.clear(); scene.background=new THREE.Color(mode==='night'?0x050713:mode==='jungle'?0x88c994:0x8fd3ff); scene.fog.color.set(mode==='night'?0x060816:mode==='jungle'?0xa1dba7:0xb9dcff); roadMat.color.set(mode==='night'?0x111821:0x242930); const ground=mesh(new THREE.PlaneGeometry(900,1600,1,1),grassMat,new THREE.Vector3(0,-.01,0),false); ground.rotation.x=-Math.PI/2; world.add(ground);
 for(let z=-760;z<760;z+=80){const road=mesh(new THREE.PlaneGeometry(18,82),mode==='night'?wetMat:roadMat,new THREE.Vector3(0,.01,z),false); road.rotation.x=-Math.PI/2; world.add(road); const lineMat=new THREE.MeshStandardMaterial({color:0xf8f4d8,emissive:mode==='night'?0x2444ff:0x000000,emissiveIntensity:mode==='night'?.5:0}); for(const x of [-3,3,0]){const mark=mesh(new THREE.PlaneGeometry(x? .18:.13, x?52:18),lineMat,new THREE.Vector3(x,.025,z),false); mark.rotation.x=-Math.PI/2; world.add(mark);} }
 for(let i=0;i<220;i++){const z=-760+Math.random()*1520, side=Math.random()>.5?1:-1, x=side*(13+Math.random()*95); if(mode==='night'&&Math.random()<.38){const b=mesh(new THREE.BoxGeometry(6+Math.random()*12,18+Math.random()*70,6+Math.random()*14),new THREE.MeshStandardMaterial({color:0x182033,roughness:.55,metalness:.2}),new THREE.Vector3(x,10,z)); world.add(b); const glow=new THREE.PointLight([0x53f5ff,0xff2bd6,0xffd166][i%3],1.1,36); glow.position.set(x,14,z); world.add(glow);} else {const trunk=mesh(new THREE.CylinderGeometry(.25,.45,3,8),new THREE.MeshStandardMaterial({color:0x5b331a}),new THREE.Vector3(x,1.5,z)); const crown=mesh(new THREE.ConeGeometry(2.5+Math.random()*2,6+Math.random()*4,9),new THREE.MeshStandardMaterial({color:mode==='jungle'?0x0f7a37:0x1e6b2a,roughness:.9}),new THREE.Vector3(x,6,z)); world.add(trunk,crown);} }
 for(let z=-700;z<700;z+=160){const sign=mesh(new THREE.BoxGeometry(2.2,1.1,.12),new THREE.MeshStandardMaterial({color:0x1667ff,metalness:.1,roughness:.35}),new THREE.Vector3(11,3,z)); const pole=mesh(new THREE.CylinderGeometry(.05,.05,3,8),new THREE.MeshStandardMaterial({color:0x888888,metalness:.8}),new THREE.Vector3(11,1.5,z)); world.add(sign,pole);} }
function renderGarage(){carList.innerHTML=cars.map(c=>{const owned=state.owned.includes(c.id),active=state.selected===c.id;return `<article class="car-card"><div class="car-art" style="--car-color:#${c.color.toString(16).padStart(6,'0')}"><i class="shine"></i><i class="wheel a"></i><i class="wheel b"></i></div><h3>${c.name}</h3><p>${c.price?c.price+' монет':'Стартовая машина'}</p>${bar('Скорость',c.speed/92)}${bar('Сцепление',c.grip/1.34)}${bar('Нитро',c.nitro/50)}<button data-buy="${c.id}" ${active?'disabled':''}>${owned?(active?'Выбрана':'Выбрать'):'Купить за '+c.price}</button></article>`}).join('');}
function bar(n,v){return `<small>${n}</small><div class="bar"><i style="width:${Math.round(v*100)}%"></i></div>`;}
function start(mode){game.mode=mode; createWorld(mode); game.running=true; game.speed=0; game.sideVel=0; game.nitro=100; game.distance=0; game.coins=[]; game.traffic=[]; show(hud);} createWorld('day');
function spawn(){if(game.coins.length<24){const coin=mesh(new THREE.TorusGeometry(.38,.11,12,28),new THREE.MeshStandardMaterial({color:0xffd447,emissive:0xffb000,emissiveIntensity:.35,metalness:.9,roughness:.18}),new THREE.Vector3((Math.floor(Math.random()*3)-1)*3,1.1,-180-Math.random()*620)); coinGroup.add(coin); game.coins.push(coin);} if(game.traffic.length<16){const tc=cars[1+Math.floor(Math.random()*(cars.length-1))], t=createCar(tc,true); t.position.set((Math.floor(Math.random()*3)-1)*3,0,-220-Math.random()*720); t.userData.speed=18+Math.random()*20; trafficGroup.add(t); game.traffic.push(t);}}
function update(dt){if(!game.running)return; const c=car(), steer=(game.keys.ArrowLeft||game.keys.KeyA?-1:0)+(game.keys.ArrowRight||game.keys.KeyD?1:0), throttle=game.keys.ArrowDown||game.keys.KeyS?-1:1, nitro=(game.keys.ControlLeft||game.keys.ControlRight)&&game.nitro>0; game.speed+=((throttle>0?c.speed*(nitro?1.32:1):0)-game.speed)*dt*(c.accel/18); if(throttle<0) game.speed-=c.brake*dt; game.speed=Math.max(0,Math.min(c.speed*1.35,game.speed)); game.nitro=THREE.MathUtils.clamp(game.nitro+(nitro?-c.nitro*dt:12*dt),0,100); const grip=c.grip*(game.drift?.45:1); game.sideVel+=steer*dt*(18/c.mass*1200)*(game.drift?1.8:1); game.sideVel*=Math.pow(grip*.72,dt*5); player.position.x=THREE.MathUtils.clamp(player.position.x+game.sideVel*dt*game.speed*.08,-7.2,7.2); player.rotation.y=THREE.MathUtils.lerp(player.rotation.y,-game.sideVel*.06-steer*.06,dt*8); game.distance+=game.speed*dt; world.position.z=(game.distance%80); spawn();
 for(const coin of [...game.coins]){coin.rotation.y+=dt*4; coin.position.z+=game.speed*dt; if(coin.position.distanceTo(player.position)<2.2){state.coins+=50; save(); sync(); coinGroup.remove(coin); game.coins.splice(game.coins.indexOf(coin),1);} if(coin.position.z>28){coinGroup.remove(coin); game.coins.splice(game.coins.indexOf(coin),1);}}
 for(const t of [...game.traffic]){t.position.z+=(game.speed-t.userData.speed)*dt; if(t.position.distanceTo(player.position)<2.8){game.speed*=.25; game.sideVel*=-.5; notify('Удар! Контролируй дистанцию.');} if(t.position.z>50){trafficGroup.remove(t); game.traffic.splice(game.traffic.indexOf(t),1);}}
 const camTarget=game.camera==='first'?new THREE.Vector3(player.position.x,2.0,player.position.z-1.25):new THREE.Vector3(player.position.x,4.8,player.position.z+9.2); const look=game.camera==='first'?new THREE.Vector3(player.position.x+game.sideVel*.18,1.7,player.position.z-18):new THREE.Vector3(player.position.x,1.2,player.position.z-8); camera.position.lerp(camTarget,dt*5); camera.lookAt(look); speedEl.textContent=Math.round(game.speed*4.4); nitroEl.textContent=Math.round(game.nitro); driveModeEl.textContent=game.drift?'Drift':'Grip'; cameraModeEl.textContent=game.camera==='first'?'1-е лицо':'3-е лицо';}
function loop(){const dt=Math.min(.033,game.clock.getDelta()); update(dt); composer.render(); requestAnimationFrame(loop);} loop();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight; camera.updateProjectionMatrix(); renderer.setSize(innerWidth,innerHeight); composer.setSize(innerWidth,innerHeight);});
document.addEventListener('keydown',e=>{game.keys[e.code]=true; if((e.code==='ShiftLeft'||e.code==='ShiftRight')&&!e.repeat)game.drift=!game.drift; if((e.code==='KeyC'||e.code==='KeyV')&&!e.repeat)game.camera=game.camera==='first'?'third':'first';}); document.addEventListener('keyup',e=>game.keys[e.code]=false);
document.addEventListener('click',e=>{const a=e.target.closest('[data-action],[data-mode],[data-buy]'); if(!a)return; if(a.dataset.action==='play')show(modes); if(a.dataset.action==='garage')show(garage); if(a.dataset.action==='menu')show(ui); if(a.dataset.action==='camera')game.camera=game.camera==='first'?'third':'first'; if(a.dataset.action==='reward1000')reward(1000); if(a.dataset.action==='reward2000')reward(2000); if(a.dataset.mode)start(a.dataset.mode); if(a.dataset.buy){const c=cars.find(x=>x.id===a.dataset.buy); if(state.owned.includes(c.id)){state.selected=c.id; rebuildPlayer();} else if(state.coins>=c.price){state.coins-=c.price; state.owned.push(c.id); state.selected=c.id; rebuildPlayer(); notify(`${c.name} куплена`);} else notify('Недостаточно монет'); save(); sync();}});
sync(); show(ui);
